### ISSUE TITLE
Side-by-Side view to compare original and revised applications

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1132] opened 2019-03-26 00:48 UTC
This is not a bug. A few team members find it difficult to read revised applications.

1) Side-by-Side view to compare original and revised text OR 2) change current green and pink highlight over text to increase readability of revised text.

**Comment by frjo** [comment] 2019-03-26 10:39
Duplicate of #748

**Closed by frjo** 2019-03-26 10:39 UTC
Labels: enhancement, ui/ux
