### ISSUE TITLE
Edit stock message to applicants 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1302] opened 2019-07-09 16:16 UTC
Account name or name of person: Di

**Is your feature request related to a problem? Please describe.**
Two suggested edits to email messages sent to applicants: 1) Please delete subheadings when these sections do not include text. In the image below, you will see applicants receive emails with section headings with no text underneath. 2) Clearly states applicants can reply to the emails the system sends out. We can add a stock message at the bottom or something to that effect

**Describe the solution you'd like**
Give PMs a slightly higher administrative authority to edit email messages sent to applicants.

**Additional context**
Subheadings in emails without text:
![image](https://user-images.githubusercontent.com/20019656/60905052-4757fa00-a242-11e9-87dc-97a558841ee5.png)

Clearly state applicant can reply to emails sent by OTF: "If you have any questions, please leave a message on your application or email us at info@opentech.fund or [reply to email]"

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Applicants

**Ideal deadline**
Date when you'd like to see this accomplished and a reason, if appropriate.

**Comment by danblah** [comment] 2019-07-09 16:27
Is the first part of this is a duplicate of https://github.com/OpenTechFund/opentech.fund/issues/1223 @fourthletter? 

How about we change the last lines to:

```
Read the determination here: <link to determination msg>
You can access your application here: <link to submission>
If you have any questions, please submit them here: <link to submissions communication tab>

If you have any issues accessing the submission system or other general inquiries, please email us at hello@opentech.fund
```

**Comment by danblah** [comment] 2019-07-09 16:29
https://github.com/OpenTechFund/opentech.fund/pull/758 is also releated.

**Comment by fourthletter** [comment] 2019-07-09 18:21
@danblah Yes, it's a duplicate. I've reached an age when I'm just repeating myself now.

**Comment by frjo** [comment] 2019-07-09 20:21
@fourthletter  @danblah Added PR where I updated the e-mail template according to the above.

The question labels with no answer in the determination e-mails I can not reproduce. The template checks so answer in not empty before printing out the question. When I test it locally it works.

Could it be that some spaces or other invisible character have sneaked their way in to the fields in question?

**Comment by danblah** [comment] 2019-07-11 15:57
> Could it be that some spaces or other invisible character have sneaked their way in to the fields in question?

That seems like a question for you. Can you check the above referenced determination to see if sneaky characters are present?

**Comment by fourthletter** [comment] 2019-07-11 17:46
@frjo Example1: message with empty spaces under subheadings: https://apply.opentech.fund/apply/submissions/4565/determination/4987/

Example 2: message with NO empty spaces under subheadings: https://apply.opentech.fund/apply/submissions/4194/determination/4791/

**Comment by fourthletter** [comment] 2019-07-11 17:49
@danblah The second part of this issue is AL wants stock emails to clearly state applicants can reply to emails sent by OTF. Example: "If you have any questions, please leave a message on your application, email us at info@opentech.fund or [**reply to email**]"

**Comment by frjo** [comment] 2019-07-11 17:51
@fourthletter I missed at first that it was the subheadings and not the question labels that was the issue. Need to read more carefully.

I will see what I can do about the subheadings. They are tricky since they just are text inserted in to the form with no relation to "sections" besides their order in the form.

The part that needs testing is the revised e-mail template. That is already on test for testing. When I put the "needs tests" label on an issue it always about testing on test.

**Comment by fourthletter** [comment] 2019-07-11 18:09
@frjo Please move forward with the e-mail template. Thank you.

**Closed** 2019-07-12 06:43 UTC
Labels: communicate, email

**Comment by frjo** [comment] 2019-07-12 06:49
Moved the subheadings issue to #1307.
