### ISSUE TITLE
Names of reviewers are not visible in detailed view

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1117] opened 2019-03-15 18:34 UTC
Reviewers signed up as primary and secondary are not visible in the detailed view. Names and the stacking order of these names are not the same from one view to the next. Here is an example: https://apply.opentech.fund/apply/submissions/3865/

Individuals signed up as primary and secondary reviews should be visible in the submission, detailed, and list view.

**Comment by frjo** [comment] 2019-03-18 11:05
Duplicate of #1109.

**Closed by frjo** 2019-03-18 11:05 UTC
Labels: WinterSprint, bug
