### ISSUE TITLE
DIFP Workflow Status Reverts

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1456] opened 2019-08-22 14:13 UTC
- Account name or name of person: Di
- Title of submission (app URLs alone are OK): I am testing DIFP on the live site. Here is the link to my test application: https://apply.opentech.fund/apply/submissions/4962/#submission-details

**Describe the bug**

**To Reproduce**
1. Go to application and see workflow status bar: https://apply.opentech.fund/apply/submissions/4962/#submission-details
2. Click on Status Update

**Expected behavior**
Staff should be able to revert status. The workflow status bar contains 13 statuses while CIF contains 4.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- Applicants

**Screenshots**
<img width="1212" alt="Screen Shot 2019-08-22 at 9 56 17 AM" src="https://user-images.githubusercontent.com/20019656/63521871-406d0a00-c4c5-11e9-89d5-d075e05882a0.png">

**Comment by fourthletter** [comment] 2019-08-23 20:11
CN in DIFP are the same as IFF & CIF except for some instances. I do not know what triggers this behavior. 

Examples: 
Test 1: https://apply.opentech.fund/apply/submissions/4964/
Test 2: https://apply.opentech.fund/apply/submissions/4964/

**Comment by danblah** [comment] 2019-09-19 16:37
Is this resolved? I'm not able to replicate this with https://apply.opentech.fund/apply/submissions/4902/. I don't see all those statuses and I see the option to revert/go back a step as expected. Am I missing something?

**Comment by fourthletter** [comment] 2019-09-19 17:47
@danblah issue is related to #1449 

This is not unique to DIFP, it's in every fund. We can revert the status for concept notes, but not for proposals.

**Comment by frjo** [comment] 2019-10-07 13:31
Duplicate of #1449

**Closed by frjo** 2019-10-07 13:31 UTC
Labels: enhancement
