### ISSUE TITLE
Review updates: reviewer consensus: dashboard review blocks

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#989] opened 2019-02-08 15:27 UTC
**Acceptance criteria**
- [x] Agreeing with a review will remove it from your list of reviews to review - Dashboard
- [x] Disagreeing with a review will not remove it from your list of reviews to review - Dashboard

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment] 2019-02-22 11:37
Hi @emullaney 

This seems to have knocked something out with the display on the 'waiting for your review' block on the dashboard. User no longer seems to see reviews here. Example: https://dev-apply.opentech.fund/apply/submissions/10/ should be showing in Lindsay Beck's dashboard. She is assigned as primary reviewer and the submission is in internal review.

Can you please take a look at this before I test this, as it is currently blocking this.

Thanks,
Maya

**Comment by todd-dembrey** [comment] 2019-02-22 14:11
@gibbsmaya This was caused by the issue @emullaney raised about image rendering errors. the PR #1054 fixes this.

This is now ready to test.

**Comment by emullaney** [comment] 2019-02-22 14:15
One reminder, that I just noticed in the code. The review will have to be in the current status of 'review' and not in 'discussion' in order to show up in that block. 

I noticed a review not showing in the list when I assigned it to Lindsay just now on dev, but it was in the 'Ready for Discussion' status, so that's why it was now showing up in the ***Waiting for your review*** list.

**Comment by gibbsmaya** [comment] 2019-02-22 14:50
Thanks both. This now works as expected.

**Comment by gibbsmaya** [comment] 2019-02-22 17:00
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work follows on from #960, applying some additional logic to a user’s dashboard block of reviews awaiting review.

Please test this against the acceptance criteria noted in the initial issue description. Note that the application you use for testing will need to be in 'internal review' in order to show in the dashboard review blocks.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment] 2019-02-26 06:31
All acceptance criteria are visible and functional. Thanks! 💥

**Comment by gibbsmaya** [comment] 2019-02-27 14:59
Great, thanks @fourthletter. Moving to @todd-dembrey ready for deployment to live.

**Closed** 2019-03-08 09:04 UTC
Labels: needs tests
