### ISSUE TITLE
can't send approved before open and close review states [High/Bug] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#745] opened 2018-11-27 13:09 UTC
-=Sensitive=-
No

-=Reporter=-
Tara  ()

-=Ideal deadline=-

-=Who's affected=-
OTF team

-=Description=-
I cannot send an invite to proposal, before first updating the status of a concept note twice, once to "Open for Review" and once to "Close Review". I don't understand the reasoning behind this and it is very annoying to do for every concept note.

-=Objective=-

-=Additiional info=-
Can we please fix this ASAP? 

-=Timestamp=-
2018-11-27T13:08:19.988Z

**Comment by frjo** [comment] 2018-11-28 11:40
Duplicate of 
https://github.com/OpenTechFund/opentech.fund/issues/725

**Closed by frjo** 2018-11-28 11:40 UTC
Labels: unsorted
